### ISSUE TITLE
Ability to remove Heroku account

### ISSUE THREAD

**Issue by Nedomas** [prisma/prisma-cloud-feedback#200]
1. If you remove Prisma authorization from the your Heroku account, trying to use that Heroku account to create Prisma server will not try to reauthorize but error as "Invalid credentials".
2. It is also not possible to remove Heroku account from Prisma. 

Therefore, it means it will not be possible to use Heroku on Prisma if you deauthorize Prisma app from your Heroku account and there's no way to reauthorize it.

**Comment by Nedomas** [comment]
This is somewhat related to https://github.com/prismagraphql/prisma-cloud-feedback/issues/193

**Comment by JamesHenry** [comment]
I just got bitten by this too.

I was doing research under my own workspace, but wanted to transfer things to the company workspace which will have billing details associated with it and the appropriate slug.

I discovered you cannot transfer things between Prisma workspaces, so then I tried deleting my personal one, unauthorizing Prisma in heroku, and starting from scratch in the company workspace.

It will not let me use the heroku account again, even though I have deleted my personal workspace and now have no way to retrieve it.

**Comment by corysimmons** [comment]
lol this 100% breaks Prisma. Please prioritize this fix.

In my case I didn't even unauthorize Heroku. I just created a Team in Heroku and suddenly Prisma breaks and I can't repair it.

Guess I'll delete my Heroku account and try again with a new one with a new email or something? :\

**Comment by Eiskis** [comment]
I also got myself "locked out"... I was having other issues (#187 and #201) and also changed my Heroku password, so as a workaround I tried relinking my account. I assumed deauthorizing the account on Heroku was the intended flow since I found no option for this on Prisma, and as a result I'm now completely stuck even though it seems the issues I was originally experiencing are resolved. There needs to be a robust way of maintaining and re-establishing the connections between accounts, otherwise I can't see myself being able to deploy anything intended for production even though on a high level I find Prisma's Heroku integration almost ideal for my project.

**Comment by corysimmons** [comment]
I ended up having to login with completely different Prisma account. :|

**Comment by ArnieGA** [comment]
I also had this problem.  In my case, creating a new server with a different name doesn't work:  it displays a popup error message saying that the credentials are invalid during the database setup process.  Additionally, I can't re-log in to Heroku from the setup wizard, since there is no option to log out from Heroku and then log back in.  I tried going to Heroku, deleting the entire original project, and start all over again:  no dice.

**Comment by Nedomas** [comment]
@ArnieGA the only way to mitigate this now is to create a new Heroku account as far as I know.

**Comment by ArnieGA** [comment]
@Nedomas wow...so it means that no matter what, once you create a server @ Prisma Cloud, even if it runs perfectly we won't be able to add new ones?

**Comment by Nedomas** [comment]
Wohoo! @ArnieGA - it looks like this might be fixed this week: https://github.com/prisma/prisma-cloud-feedback/issues/226#issuecomment-435397716

**Comment by lydiahallie** [comment]
This feature has been implemented by now! You can now link an Heroku account to multiple workspaces, and delete an account from a workspace.

**Comment by i8ramin** [comment]
I can;t seem to unlink my Heroku account from a workspace, so not sure if this issue is entirely fixed. Possibly related issue: https://github.com/prisma/prisma-cloud-feedback/issues/191

**Comment by lydiahallie** [comment]
@i8ramin Thank you for letting us know! Unlinking a Heroku account from a workspace is supposed to work. Would you be able to give more information about the behavior on your side?
